const DEFAULT_KEEP_RECENT = 12;
const DEFAULT_MAX_CHARS = 14000;

function normalizeContent(content) {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    return content.map(part => {
      if (!part) return '';
      if (typeof part.text === 'string') return part.text;
      if (part.image_url?.url) return '[image]';
      return '';
    }).filter(Boolean).join('\n');
  }
  return '';
}

function compact(value, maxChars = 700) {
  const text = String(value || '').replace(/\s+/g, ' ').trim();
  if (text.length <= maxChars) return text;
  return `${text.slice(0, maxChars)}...`;
}

export function estimateConversationChars(entries = []) {
  return entries.reduce((sum, entry) => sum + normalizeContent(entry?.content).length, 0);
}

export function buildConversationSummary(entries = [], options = {}) {
  const maxItems = Math.max(1, Number(options.maxItems || 18));
  const maxEntryChars = Math.max(120, Number(options.maxEntryChars || 520));
  const selected = entries.slice(-maxItems);

  if (selected.length === 0) return '';

  const lines = selected.map((entry, index) => {
    const role = entry?.role || 'unknown';
    const text = compact(normalizeContent(entry?.content), maxEntryChars);
    return `${index + 1}. ${role}: ${text || '[empty]'}`;
  });

  return [
    'Conversation summary generated by Winter context compression.',
    ...lines,
  ].join('\n');
}

export function compressConversation(entries = [], options = {}) {
  const keepRecent = Math.max(2, Number(options.keepRecent || DEFAULT_KEEP_RECENT));
  const maxChars = Math.max(500, Number(options.maxChars || DEFAULT_MAX_CHARS));
  const totalChars = estimateConversationChars(entries);

  if (entries.length <= keepRecent || totalChars <= maxChars) {
    return {
      compressed: false,
      summary: '',
      recent: entries,
      omittedCount: 0,
      totalChars,
    };
  }

  const older = entries.slice(0, -keepRecent);
  const recent = entries.slice(-keepRecent);

  return {
    compressed: true,
    summary: buildConversationSummary(older, options),
    recent,
    omittedCount: older.length,
    totalChars,
  };
}
