import { promises as fs } from 'fs';
import path from 'path';
import crypto from 'crypto';

export const DEFAULT_CHUNK_TOKENS = 3000;
export const APPROX_CHARS_PER_TOKEN = 4;

export function estimateTokens(value = '') {
  return Math.max(1, Math.ceil(String(value ?? '').length / APPROX_CHARS_PER_TOKEN));
}

export function slugify(value = 'note') {
  const slug = String(value || 'note')
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
  return slug || 'note';
}

export function toPosixPath(value = '') {
  return String(value).split(path.sep).join('/');
}

export function buildWikiLink(relativeFilePath = '') {
  const withoutExt = toPosixPath(relativeFilePath).replace(/\.md$/i, '');
  return `[[${withoutExt}]]`;
}

export function chunkMarkdown(markdown = '', maxTokens = DEFAULT_CHUNK_TOKENS) {
  const text = String(markdown ?? '');
  const maxChars = Math.max(800, maxTokens * APPROX_CHARS_PER_TOKEN);
  if (text.length <= maxChars) return [text];

  const chunks = [];
  let offset = 0;
  while (offset < text.length) {
    let end = Math.min(text.length, offset + maxChars);
    if (end < text.length) {
      const slice = text.slice(offset, end);
      const fence = Math.max(slice.lastIndexOf('\n## '), slice.lastIndexOf('\n# '));
      const paragraph = slice.lastIndexOf('\n\n');
      const line = slice.lastIndexOf('\n');
      const cut = [fence, paragraph, line].find(index => index > Math.floor(maxChars * 0.55));
      if (cut) end = offset + cut;
    }
    chunks.push(text.slice(offset, end).trimEnd());
    offset = end;
    while (text[offset] === '\n') offset += 1;
  }

  return chunks.filter(Boolean);
}

function yamlValue(value) {
  if (value === undefined || value === null) return '""';
  const text = String(value).replaceAll('"', '\\"').replace(/\r?\n/g, ' ');
  return `"${text}"`;
}

function renderFrontmatter(metadata = {}) {
  const lines = ['---'];
  for (const [key, value] of Object.entries(metadata)) {
    if (Array.isArray(value)) {
      lines.push(`${key}:`);
      for (const item of value) lines.push(`  - ${yamlValue(item)}`);
    } else {
      lines.push(`${key}: ${yamlValue(value)}`);
    }
  }
  lines.push('---', '');
  return lines.join('\n');
}

export class WikiMemoryStore {
  constructor({
    projectPath = process.cwd(),
    rootDir = path.join(projectPath, '.winter', 'memory'),
    maxChunkTokens = DEFAULT_CHUNK_TOKENS,
    now = () => new Date(),
  } = {}) {
    this.projectPath = path.resolve(projectPath);
    this.rootDir = path.resolve(rootDir);
    this.maxChunkTokens = maxChunkTokens;
    this.now = now;
  }

  async ensureRoot() {
    await fs.mkdir(this.rootDir, { recursive: true });
    await fs.mkdir(path.join(this.rootDir, 'tool-output'), { recursive: true });
    await this.ensureVaultReadme();
  }

  async ensureVaultReadme() {
    const readmePath = path.join(this.rootDir, 'README.md');
    try {
      await fs.access(readmePath);
    } catch {
      await fs.writeFile(readmePath, [
        '# Winter Memory Vault',
        '',
        'Obsidian-style markdown notes generated by Winter.',
        '',
        '- [[index]]',
        '- [[tool-output/index]]',
        '',
      ].join('\n'), 'utf8');
    }
  }

  async appendIndex(relativePath, title, metadata = {}) {
    const indexPath = path.join(this.rootDir, 'index.md');
    const type = metadata.type || 'note';
    const line = `- ${buildWikiLink(relativePath)} - ${title} (${type})`;
    let current = '';
    try {
      current = await fs.readFile(indexPath, 'utf8');
    } catch {
      current = '# Memory Index\n\n';
    }
    if (!current.includes(line)) {
      await fs.writeFile(indexPath, `${current.trimEnd()}\n${line}\n`, 'utf8');
    }
  }

  async appendNamespaceIndex(namespace, relativePaths, title, metadata = {}) {
    const indexPath = path.join(this.rootDir, namespace, 'index.md');
    await fs.mkdir(path.dirname(indexPath), { recursive: true });
    let current = '';
    try {
      current = await fs.readFile(indexPath, 'utf8');
    } catch {
      current = `# ${namespace}\n\nBacklinks: [[index]]\n\n`;
    }
    const links = relativePaths.map(file => buildWikiLink(file)).join(', ');
    const line = `- ${links} - ${title} (${metadata.tool || metadata.type || 'note'})`;
    if (!current.includes(line)) {
      await fs.writeFile(indexPath, `${current.trimEnd()}\n${line}\n`, 'utf8');
    }
  }

  async saveMarkdownChunks({
    title = 'Memory note',
    markdown = '',
    type = 'note',
    namespace = 'notes',
    metadata = {},
  } = {}) {
    await this.ensureRoot();

    const createdAt = this.now().toISOString();
    const date = createdAt.slice(0, 10);
    const id = crypto.createHash('sha1')
      .update(`${createdAt}\n${title}\n${markdown}`)
      .digest('hex')
      .slice(0, 12);
    const baseSlug = `${slugify(title)}-${id}`;
    const chunks = chunkMarkdown(markdown, this.maxChunkTokens);
    const dir = path.join(this.rootDir, namespace, date);
    await fs.mkdir(dir, { recursive: true });

    const files = [];
    for (let index = 0; index < chunks.length; index += 1) {
      const part = index + 1;
      const fileName = `${baseSlug}-part-${String(part).padStart(3, '0')}.md`;
      const filePath = path.join(dir, fileName);
      const relativePath = toPosixPath(path.relative(this.rootDir, filePath));
      const frontmatter = renderFrontmatter({
        id,
        type,
        title,
        created_at: createdAt,
        chunk_tokens_est: estimateTokens(chunks[index]),
        total_tokens_est: estimateTokens(markdown),
        part,
        parts: chunks.length,
        ...metadata,
      });
      const body = [
        frontmatter,
        `# ${title}`,
        '',
        `Backlinks: [[index]], [[${namespace}/index]]`,
        '',
        chunks[index],
        '',
      ].join('\n');
      await fs.writeFile(filePath, body, 'utf8');
      files.push({
        path: filePath,
        relativePath,
        wikiLink: buildWikiLink(relativePath),
        tokensEst: estimateTokens(chunks[index]),
        part,
      });
    }

    if (files[0]) {
      await this.appendIndex(files[0].relativePath, title, { type, ...metadata });
      await this.appendNamespaceIndex(namespace, files.map(file => file.relativePath), title, { type, ...metadata });
    }

    return {
      id,
      rootDir: this.rootDir,
      files,
      links: files.map(file => file.wikiLink),
      parts: files.length,
      totalTokensEst: estimateTokens(markdown),
    };
  }
}
